const sidebars = {
    docs: [
        {
            type: 'category',
            label: 'Getting Started',
            items: ['getting-started/quick-start'],
        },
        {
            type: 'category',
            label: 'Architecture',
            items: [
                'architecture/overview',
                'architecture/specifications',
                'architecture/database',
            ],
        },
        {
            type: 'category',
            label: 'Project Management',
            items: [
                'project/roadmap',
                'project/phases',
                {
                    type: 'category',
                    label: 'Issues',
                    items: [
                        'project/issues/creating-issues',
                        'project/issues/templates',
                        // We can autogenerate the rest of the issues folder if desired,
                        // or just point to the folder to include everything in it.
                        {
                            type: 'autogenerated',
                            dirName: 'project/issues',
                        },
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: 'Features',
            items: ['features/landing'],
        },
    ],
};

export default sidebars;
